[project]
name = "spidey-pipeline-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Devanshi Parmar", email = "dparmar1@charlotte.edu" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "joblib>=1.6.0",
    "modal>=1.5.5",
    "pandas>=3.0.5",
    "pydantic>=2",
    "scikit-learn>=1.9.1",
    "uvicorn>=0.53.0",
]

[project.scripts]
spidey-pipeline-api = "spidey_pipeline_api:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
